### ISSUE TITLE
登录提示`解析出错`：www.jmapinode.biz 

### ISSUE THREAD

**Issue by eve2ptp** [tonquer/JMComic-qt#101]
### 操作系统（如MacOS 10.15）
> Win10

### 网络环境（移动，联通，电信，移动宽带，联通宽带，电信宽带，等等..）
> 电信

### 问题描述（简要描述发生的问题）
> 使用代理仍然无法正确解析域名（软件调用的接口能正常跳转到jm官网）

### 复现步骤（详细描述导致问题产生的操作步骤，如果能稳定复现）
> 设置好代理，不适用分流，点击登录

### 日志提交（问题截图或者日志，日志在logs目录）
>
```python
2024-05-11 22:49:25,556 - start.py[line:71] - WARNING: init scene ratio: 1.25
2024-05-11 22:49:25,790 - download_db.py[line:45] - WARNING: duplicate column name: tick Unable to execute statement
2024-05-11 22:49:26,446 - setting_view.py[line:467] - WARNING: waifu2x GPU: ['Intel(R) UHD Graphics 770'],select: Intel(R) UHD Graphics 770,use cpu num: 0
2024-05-11 22:49:26,446 - main_view.py[line:165] - WARNING: Waifu2x init:0, encode:0, version:1.1.6, code:0, cpuNum:0/20, gpuNum:1, gpuList:['Intel(R) UHD Graphics 770']
2024-05-11 22:49:27,845 - server.py[line:225] - WARNING: https://18comic-palworld.club RequestsError("Failed to perform, ErrCode: 35, Reason: 'BoringSSL SSL_connect: Connection was reset in connection to 18comic-palworld.club:443 '. This may be a libcurl error, See https://curl.se/libcurl/c/libcurl-errors.html first for more details.")
2024-05-11 22:49:28,005 - user_handler.py[line:247] - WARNING: 登陆失败！！！, code:404, text:<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>404 Not Found</title>
</head><body>
<h1>Not Found</h1>
<p>The requested URL was not found on this server.</p>
<hr>
<address>Apache Server at www.jmapinode.biz Port 80</address>
</body></html>

2024-05-11 22:49:28,005 - user_handler.py[line:248] - ERROR: Expecting value: line 1 column 1 (char 0)
Traceback (most recent call last):
  File "server\user_handler.py", line 219, in __call__
  File "json\__init__.py", line 348, in loads
  File "json\decoder.py", line 337, in decode
  File "json\decoder.py", line 355, in raw_decode
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
2024-05-11 22:49:28,217 - server.py[line:225] - WARNING: https://18comic-palworld.club/login RequestsError("Failed to perform, ErrCode: 35, Reason: 'BoringSSL SSL_connect: Connection was reset in connection to 18comic-palworld.club:443 '. This may be a libcurl error, See https://curl.se/libcurl/c/libcurl-errors.html first for more details.")
```

www.jmapinode.biz 这个域名导致的

**Comment by tonquer** [comment]
换分流3，4
