### ISSUE TITLE
本地漫画偶尔错误，最新版

### ISSUE THREAD

**Issue by hskshd** [tonquer/JMComic-qt#106]
win10，移动宽带，偶尔划着划着跳出一个标题为错误的框，关闭这个框继续看的话会只要划几页就出错误
界面图片：
![QQ图片20240531203122](https://github.com/tonquer/JMComic-qt/assets/168625372/cc2180be-a49e-4705-abc4-a83f1538097a)
![QQ图片20240531203122](https://github.com/tonquer/JMComic-qt/assets/168625372/9cb7270e-116a-4698-8e5b-54280dcdb3f8)
界面内容（例子）：
Error（标题）
Traceback (most recent call last)：
 File "view\read\read_graphics.py",line 887,in ChangeLastPage
 File "view\read\read_graphics.py",line 928,in ClearOtherPicture
 File "view\read\read_graphics.py",line 705,in SetPixlem
 File "view\read\read_graphics.py",line 628,in PixmapToLabel
 File "view\read\read_graphics.py",line 602,in GetLabellndexError: liost indexout of range
日志一
[20240606.log](https://github.com/user-attachments/files/15753095/20240606.log)
正文：
2024-06-06 22:07:42,571 - start.py[line:71] - WARNING: init scene ratio: 1.0
2024-06-06 22:07:43,440 - download_db.py[line:45] - WARNING: duplicate column name: tick Unable to execute statement
2024-06-06 22:07:45,865 - setting_view.py[line:473] - WARNING: waifu2x GPU: ['Intel(R) UHD Graphics 620'],select: Intel(R) UHD Graphics 620,use cpu num: 0
2024-06-06 22:07:45,867 - main_view.py[line:200] - WARNING: Waifu2x init:0, encode:0, version:1.1.6, code:0, cpuNum:0/4, gpuNum:1, gpuList:['Intel(R) UHD Graphics 620']
2024-06-06 22:07:45,950 - server.py[line:229] - WARNING: https://18-comicblade.art RequestsError("Failed to perform, ErrCode: 6, Reason: 'Could not resolve host: 18-comicblade.art'. This may be a libcurl error, See https://curl.se/libcurl/c/libcurl-errors.html first for more details.")
2024-06-06 22:07:45,959 - server.py[line:229] - WARNING: https://18-comicblade.art/login RequestsError("Failed to perform, ErrCode: 6, Reason: 'Could not resolve host: 18-comicblade.art'. This may be a libcurl error, See https://curl.se/libcurl/c/libcurl-errors.html first for more details.")
2024-06-06 22:07:51,389 - tool.py[line:30] - WARNING: CTime consume:109 ms, LoadCache.E:/缓存\cache\cover/518074.webp
2024-06-06 22:07:51,399 - tool.py[line:30] - WARNING: CTime consume:104 ms, LoadCache.E:/缓存\cache\cover/558392.jpg
2024-06-06 23:50:58,534 - start.py[line:71] - WARNING: init scene ratio: 1.0
2024-06-06 23:50:59,409 - download_db.py[line:45] - WARNING: duplicate column name: tick Unable to execute statement
2024-06-06 23:51:01,392 - setting_view.py[line:473] - WARNING: waifu2x GPU: ['Intel(R) UHD Graphics 620'],select: Intel(R) UHD Graphics 620,use cpu num: 0
2024-06-06 23:51:01,392 - main_view.py[line:200] - WARNING: Waifu2x init:0, encode:0, version:1.1.6, code:0, cpuNum:0/4, gpuNum:1, gpuList:['Intel(R) UHD Graphics 620']
2024-06-06 23:51:01,517 - server.py[line:229] - WARNING: https://18-comicblade.art RequestsError("Failed to perform, ErrCode: 6, Reason: 'Could not resolve host: 18-comicblade.art'. This may be a libcurl error, See https://curl.se/libcurl/c/libcurl-errors.html first for more details.")
2024-06-06 23:51:01,533 - server.py[line:229] - WARNING: https://18-comicblade.art/login RequestsError("Failed to perform, ErrCode: 6, Reason: 'Could not resolve host: 18-comicblade.art'. This may be a libcurl error, See https://curl.se/libcurl/c/libcurl-errors.html first for more details.")
2024-06-06 23:51:14,835 - tool.py[line:30] - WARNING: CTime consume:124 ms, LoadCache.E:/缓存\cache\cover/400220.jpg
2024-06-06 23:51:14,835 - tool.py[line:30] - WARNING: CTime consume:124 ms, LoadCache.E:/缓存\cache\cover/554258.jpg
2024-06-06 23:51:14,835 - tool.py[line:30] - WARNING: CTime consume:109 ms, LoadCache.E:/缓存\cache\cover/202784.jpg
2024-06-06 23:51:14,882 - tool.py[line:30] - WARNING: CTime consume:156 ms, LoadCache.E:/缓存\cache\cover/518074.webp
2024-06-06 23:52:12,225 - tool.py[line:30] - WARNING: CTime consume:120 ms, LoadCache.E:/缓存\cache\cover/450324.webp
2024-06-06 23:52:12,235 - tool.py[line:30] - WARNING: CTime consume:129 ms, LoadCache.E:/缓存\cache\cover/576538.jpg
2024-06-06 23:52:14,212 - tool.py[line:30] - WARNING: CTime consume:106 ms, LoadCache.E:/缓存\cache\cover/534712.webp
2024-06-06 23:52:14,222 - tool.py[line:30] - WARNING: CTime consume:118 ms, LoadCache.E:/缓存\cache\cover/534713.webp
2024-06-06 23:52:14,963 - tool.py[line:30] - WARNING: CTime consume:100 ms, LoadCache.E:/缓存\cache\cover/509306.webp
2024-06-06 23:52:14,977 - tool.py[line:30] - WARNING: CTime consume:113 ms, LoadCache.E:/缓存\cache\cover/504851.webp
2024-06-06 23:52:14,977 - tool.py[line:30] - WARNING: CTime consume:112 ms, LoadCache.E:/缓存\cache\cover/504835.webp
2024-06-06 23:53:28,867 - tool.py[line:44] - WARNING: time_me consume,261 ms, <view.tool.local_read_view.LocalReadView(0x16a15780e70, name="localReadView") at 0x0000016A16674EC8>.ShowPages
2024-06-06 23:58:34,894 - start.py[line:92] - ERROR: Traceback (most recent call last):
  File "view\read\read_graphics.py", line 902, in ChangeNextPage
  File "view\read\read_graphics.py", line 928, in ClearOtherPictureShow
  File "view\read\read_graphics.py", line 705, in SetPixIem
  File "view\read\read_graphics.py", line 628, in PixmapToLabel
  File "view\read\read_graphics.py", line 602, in GetLabel
IndexError: list index out of range
NoneType: None
2024-06-07 00:01:53,218 - start.py[line:92] - ERROR: Traceback (most recent call last):
  File "view\read\read_graphics.py", line 902, in ChangeNextPage
  File "view\read\read_graphics.py", line 928, in ClearOtherPictureShow
  File "view\read\read_graphics.py", line 705, in SetPixIem
  File "view\read\read_graphics.py", line 628, in PixmapToLabel
  File "view\read\read_graphics.py", line 602, in GetLabel
IndexError: list index out of range
NoneType: None
2024-06-07 00:01:59,728 - start.py[line:92] - ERROR: Traceback (most recent call last):
  File "view\read\read_graphics.py", line 902, in ChangeNextPage
  File "view\read\read_graphics.py", line 928, in ClearOtherPictureShow
  File "view\read\read_graphics.py", line 705, in SetPixIem
  File "view\read\read_graphics.py", line 628, in PixmapToLabel
  File "view\read\read_graphics.py", line 602, in GetLabel
IndexError: list index out of range
NoneType: None
2024-06-07 00:02:05,227 - start.py[line:92] - ERROR: Traceback (most recent call last):
  File "view\read\read_graphics.py", line 902, in ChangeNextPage
  File "view\read\read_graphics.py", line 928, in ClearOtherPictureShow
  File "view\read\read_graphics.py", line 705, in SetPixIem
  File "view\read\read_graphics.py", line 628, in PixmapToLabel
  File "view\read\read_graphics.py", line 602, in GetLabel
IndexError: list index out of range
NoneType: None
2024-06-07 00:02:16,056 - start.py[line:92] - ERROR: Traceback (most recent call last):
  File "view\read\read_graphics.py", line 902, in ChangeNextPage
  File "view\read\read_graphics.py", line 928, in ClearOtherPictureShow
  File "view\read\read_graphics.py", line 705, in SetPixIem
  File "view\read\read_graphics.py", line 628, in PixmapToLabel
  File "view\read\read_graphics.py", line 602, in GetLabel
IndexError: list index out of range
NoneType: None
2024-06-07 00:02:18,623 - start.py[line:92] - ERROR: Traceback (most recent call last):
  File "view\read\read_graphics.py", line 887, in ChangeLastPage
  File "view\read\read_graphics.py", line 928, in ClearOtherPictureShow
  File "view\read\read_graphics.py", line 705, in SetPixIem
  File "view\read\read_graphics.py", line 628, in PixmapToLabel
  File "view\read\read_graphics.py", line 602, in GetLabel
IndexError: list index out of range
NoneType: None
2024-06-07 00:02:23,156 - start.py[line:92] - ERROR: Traceback (most recent call last):
  File "view\read\read_graphics.py", line 887, in ChangeLastPage
  File "view\read\read_graphics.py", line 928, in ClearOtherPictureShow
  File "view\read\read_graphics.py", line 705, in SetPixIem
  File "view\read\read_graphics.py", line 628, in PixmapToLabel
  File "view\read\read_graphics.py", line 602, in GetLabel
IndexError: list index out of range
NoneType: None

日志二
[20240609.log](https://github.com/user-attachments/files/15753096/20240609.log)
正文：
2024-06-09 09:07:24,001 - start.py[line:71] - WARNING: init scene ratio: 1.0
2024-06-09 09:07:24,672 - download_db.py[line:45] - WARNING: duplicate column name: tick Unable to execute statement
2024-06-09 09:07:26,599 - setting_view.py[line:473] - WARNING: waifu2x GPU: ['Intel(R) UHD Graphics 620'],select: Intel(R) UHD Graphics 620,use cpu num: 0
2024-06-09 09:07:26,599 - main_view.py[line:200] - WARNING: Waifu2x init:0, encode:0, version:1.1.6, code:0, cpuNum:0/4, gpuNum:1, gpuList:['Intel(R) UHD Graphics 620']
2024-06-09 09:07:26,693 - server.py[line:229] - WARNING: https://18-comicblade.art RequestsError("Failed to perform, ErrCode: 6, Reason: 'Could not resolve host: 18-comicblade.art'. This may be a libcurl error, See https://curl.se/libcurl/c/libcurl-errors.html first for more details.")
2024-06-09 09:07:26,855 - server.py[line:229] - WARNING: https://18-comicblade.art/login RequestsError("Failed to perform, ErrCode: 6, Reason: 'Could not resolve host: 18-comicblade.art'. This may be a libcurl error, See https://curl.se/libcurl/c/libcurl-errors.html first for more details.")
2024-06-09 09:07:32,304 - tool.py[line:30] - WARNING: CTime consume:112 ms, LoadCache.E:/缓存\cache\cover/550437.webp
2024-06-09 09:07:32,325 - tool.py[line:30] - WARNING: CTime consume:130 ms, LoadCache.E:/缓存\cache\cover/443933.webp
2024-06-09 09:08:04,684 - tool.py[line:30] - WARNING: CTime consume:116 ms, LoadCache.E:/缓存\cache\cover/568150.webp
2024-06-09 09:08:18,398 - tool.py[line:44] - WARNING: time_me consume,255 ms, <view.tool.local_read_view.LocalReadView(0x1f9951edd60, name="localReadView") at 0x000001F9960C4E08>.ShowPages
2024-06-09 22:49:43,962 - start.py[line:71] - WARNING: init scene ratio: 1.0
2024-06-09 22:49:44,528 - download_db.py[line:45] - WARNING: duplicate column name: tick Unable to execute statement
2024-06-09 22:49:46,176 - setting_view.py[line:473] - WARNING: waifu2x GPU: ['Intel(R) UHD Graphics 620'],select: Intel(R) UHD Graphics 620,use cpu num: 0
2024-06-09 22:49:46,176 - main_view.py[line:200] - WARNING: Waifu2x init:0, encode:0, version:1.1.6, code:0, cpuNum:0/4, gpuNum:1, gpuList:['Intel(R) UHD Graphics 620']
2024-06-09 22:49:46,265 - server.py[line:229] - WARNING: https://18-comicblade.art RequestsError("Failed to perform, ErrCode: 6, Reason: 'Could not resolve host: 18-comicblade.art'. This may be a libcurl error, See https://curl.se/libcurl/c/libcurl-errors.html first for more details.")
2024-06-09 22:49:46,430 - server.py[line:229] - WARNING: https://18-comicblade.art/login RequestsError("Failed to perform, ErrCode: 6, Reason: 'Could not resolve host: 18-comicblade.art'. This may be a libcurl error, See https://curl.se/libcurl/c/libcurl-errors.html first for more details.")
2024-06-09 22:50:19,133 - start.py[line:92] - ERROR: Traceback (most recent call last):
  File "component\scroll\read_scroll.py", line 123, in Finished
  File "component\scroll\read_scroll.py", line 249, in OnValueChange
TypeError: '<' not supported between instances of 'int' and 'NoneType'
NoneType: None
2024-06-09 22:50:40,339 - tool.py[line:44] - WARNING: time_me consume,249 ms, <view.tool.local_read_view.LocalReadView(0x16f8fa92d20, name="localReadView") at 0x0000016F90C04FC8>.ShowPages
2024-06-09 22:52:18,886 - task_qimage.py[line:95] - WARNING: [Task] not find taskId:79
2024-06-09 22:52:45,710 - tool.py[line:44] - WARNING: time_me consume,127 ms, <view.read.read_view.ReadView(0x16f9305c270, name="readView") at 0x0000016F92C3E908>.ShowImg
2024-06-09 22:52:46,660 - task_qimage.py[line:95] - WARNING: [Task] not find taskId:252
2024-06-09 22:52:52,699 - task_qimage.py[line:95] - WARNING: [Task] not find taskId:314
2024-06-09 23:00:55,494 - tool.py[line:30] - WARNING: CTime consume:101 ms, ReadTool.
2024-06-09 23:00:57,075 - tool.py[line:30] - WARNING: CTime consume:116 ms, ReadTool.
2024-06-09 23:01:56,059 - tool.py[line:30] - WARNING: CTime consume:123 ms, ReadTool.
2024-06-09 23:02:10,991 - tool.py[line:30] - WARNING: CTime consume:105 ms, ReadTool.
2024-06-09 23:02:57,659 - tool.py[line:30] - WARNING: CTime consume:123 ms, ReadTool.
2024-06-09 23:05:32,329 - task_qimage.py[line:95] - WARNING: [Task] not find taskId:652
2024-06-09 23:05:32,567 - task_qimage.py[line:95] - WARNING: [Task] not find taskId:653
2024-06-09 23:05:32,570 - task_qimage.py[line:95] - WARNING: [Task] not find taskId:654
2024-06-09 23:05:33,668 - tool.py[line:30] - WARNING: CTime consume:132 ms, ReadTool.
2024-06-09 23:05:34,936 - tool.py[line:30] - WARNING: CTime consume:107 ms, ReadTool.
2024-06-09 23:05:35,045 - tool.py[line:30] - WARNING: CTime consume:107 ms, ReadTool.
2024-06-09 23:05:35,176 - tool.py[line:30] - WARNING: CTime consume:102 ms, ReadTool.
2024-06-09 23:05:35,508 - tool.py[line:30] - WARNING: CTime consume:100 ms, ReadTool.
2024-06-09 23:05:53,851 - tool.py[line:30] - WARNING: CTime consume:104 ms, ReadTool.
2024-06-09 23:05:53,987 - tool.py[line:30] - WARNING: CTime consume:101 ms, ReadTool.
2024-06-09 23:06:20,339 - tool.py[line:30] - WARNING: CTime consume:102 ms, ReadTool.
2024-06-09 23:06:20,478 - tool.py[line:30] - WARNING: CTime consume:115 ms, ReadTool.
2024-06-09 23:06:20,614 - tool.py[line:30] - WARNING: CTime consume:115 ms, ReadTool.
2024-06-09 23:06:20,876 - tool.py[line:30] - WARNING: CTime consume:118 ms, ReadTool.
2024-06-09 23:06:21,018 - tool.py[line:30] - WARNING: CTime consume:106 ms, ReadTool.
2024-06-09 23:06:21,348 - tool.py[line:30] - WARNING: CTime consume:102 ms, ReadTool.
2024-06-09 23:06:21,481 - tool.py[line:30] - WARNING: CTime consume:102 ms, ReadTool.
2024-06-09 23:06:21,601 - tool.py[line:30] - WARNING: CTime consume:118 ms, ReadTool.
2024-06-09 23:06:21,768 - tool.py[line:30] - WARNING: CTime consume:110 ms, ReadTool.

**Comment by tonquer** [comment]
是多章节的，看几章的会出现吗

**Comment by hskshd** [comment]
> 是多章节的，看几章的会出现吗

是的

**Comment by tonquer** [comment]
更新试试
https://github.com/tonquer/JMComic-qt/releases/tag/v1.2.3

**Comment by hskshd** [comment]
OK，谢谢你，我试试，有问题再反馈

获取Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
