### ISSUE TITLE
下载时文件名过长

### ISSUE THREAD

**Issue by yisishoujo** [tonquer/JMComic-qt#117]
```
Traceback (most recent call last):
  File "server/user_handler.py", line 891, in __call__
  File "os.py", line 213, in makedirs
  File "os.py", line 213, in makedirs
  File "os.py", line 223, in makedirs
OSError: [Errno 36] 文件名过长: '/home/xxxxxxxxxxxxx/commies/作为被背叛了的S级冒险者的我、决定成立一个只有我所爱的奴隶女孩子们的后宫公会 [柊咲川田晓生ナイロン] 里切られたSランク冒险者の俺は、爱する奴隷の彼女らと共に奴隷だけのハーレムギルドを作る'
```

**Comment by tonquer** [comment]
v1.2.5尝试修复了

**Comment by yisishoujo** [comment]
好像是修复了，但是linux的appimage有问题，直接执行提示找不到JMcomic
```
❯ ./jmcomic_v1.2.5_linux-x86_64.AppImage
JMComic
/tmp/.mount_jmcomiAOq2NK/AppRun: 第 13 行：exec: JMComic: 未找到
```
我是解压后把JMComic.desktop里面改成`Exec=usr/bin/start`才跑起来的
