### ISSUE TITLE
1.2.3升级1.2.5后打开出现错误

### ISSUE THREAD

**Issue by 2721616719** [tonquer/JMComic-qt#129]
### 操作系统（如MacOS 10.15）
>Windows 11, version 23H2

### 网络环境（移动，联通，电信，移动宽带，联通宽带，电信宽带，等等..）
>移动宽带

### 问题描述（简要描述发生的问题）
>升级版本后打开出现报错

### 复现步骤（详细描述导致问题产生的操作步骤，如果能稳定复现）
>替换CHANGELOG，LICENSE，start.exe文件为新版1.2.5后，打开出现报错。回退到1.2.3版本为正常。1.2.5版删除data中config.ini文件后才可以正常打开。

### 日志提交（问题截图或者日志，日志在logs目录）
>2024-10-27 00:44:18,483 - start.py[line:71] - WARNING: init scene ratio: 1.0
2024-10-27 00:44:19,143 - start.py[line:83] - ERROR: 'PySide6.QtWidgets.QScrollerProperties' object has no attribute 'MousePressEventDelay'
Traceback (most recent call last):
  File "start.py", line 78, in <module>
  File "view\main\main_view.py", line 31, in __init__
  File "component\widget\main_widget.py", line 68, in __init__
  File "interface\ui_main.py", line 101, in setupUi
  File "view\index\index_view.py", line 18, in __init__
  File "interface\ui_index.py", line 38, in setupUi
  File "component\list\comic_list_widget.py", line 19, in __init__
  File "component\list\base_list_widget.py", line 29, in __init__
AttributeError: 'PySide6.QtWidgets.QScrollerProperties' object has no attribute 'MousePressEventDelay'

**Comment by tonquer** [comment]
设置中打开触控优化导致的问题，待修复
