### ISSUE TITLE
请问1.0.8打开这个报错要怎么解决。。

### ISSUE THREAD

**Issue by matocool** [tonquer/JMComic-qt#37]
Traceback (most recent call last):
  File "start.py", line 78, in <module>
  File "view\main\main_view.py", line 31, in __init__
  File "component\widget\main_widget.py", line 22, in __init__
  File "interface\ui_main_windows.py", line 105, in setupUi
  File "view\tool\local_read_view.py", line 42, in __init__
  File "view\tool\local_read_db.py", line 14, in __init__
sqlite3.OperationalError: unable to open database file

**Comment by tonquer** [comment]
重新发布了 再试试，https://github.com/tonquer/JMComic-qt/releases/tag/v1.0.8
