### ISSUE TITLE
新版本开启webp转png功能后下载文件夹为空

### ISSUE THREAD

**Issue by fuchaohan** [tonquer/JMComic-qt#82]
### 操作系统（如MacOS 10.15）
>

### 网络环境（移动，联通，电信，移动宽带，联通宽带，电信宽带，等等..）
>

### 问题描述（简要描述发生的问题）
>
上一个版本保存png功能正常，最近发现下载后没有文件，关闭转换png功能能正常下载webp

### 复现步骤（详细描述导致问题产生的操作步骤，如果能稳定复现）
>

### 日志提交（问题截图或者日志，日志在logs目录）
>
Traceback (most recent call last):
  File "server\user_handler.py", line 773, in __call__
  File "requests\models.py", line 765, in generate
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='cdn-msp.jmapiproxy1.cc', port=443): Read timed out.
2023-11-29 23:32:40,610 - user_handler.py[line:838] - ERROR: HTTPSConnectionPool(host='cdn-msp.jmapiproxy1.cc', port=443): Read timed out.
Traceback (most recent call last):
  File "urllib3\response.py", line 436, in _error_catcher
  File "urllib3\response.py", line 763, in read_chunked
  File "urllib3\response.py", line 693, in _update_chunk_length
  File "socket.py", line 589, in readinto
  File "ssl.py", line 1071, in recv_into
  File "ssl.py", line 929, in read
socket.timeout: The read operation timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "requests\models.py", line 758, in generate
  File "urllib3\response.py", line 571, in stream
  File "urllib3\response.py", line 792, in read_chunked
  File "contextlib.py", line 130, in __exit__
  File "urllib3\response.py", line 441, in _error_catcher
urllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(host='cdn-msp.jmapiproxy1.cc', port=443): Read timed out.

**Comment by Overflowu7** [comment]
安卓版最新能用的版本去哪下载能不能麻烦指个路啊 QAQ

**Comment by tonquer** [comment]
https://github.com/tonquer/JMComic-qt/releases/tag/v1.1.8.1
