### ISSUE TITLE
登陆时 出现解析出错了 报错提醒

### ISSUE THREAD

**Issue by huaiyi255** [tonquer/JMComic-qt#9]
### 操作系统（如MacOS 10.15）
>win10 2021h

### 网络环境（移动，联通，电信，移动宽带，联通宽带，电信宽带，等等..）
>联通宽带

### 问题描述（简要描述发生的问题）
>登陆时 出现解析出错了 报错提醒

### 复现步骤（详细描述导致问题产生的操作步骤，如果能稳定复现）
>

### 日志提交（问题截图或者日志，日志在logs目录）
>
![image](https://user-images.githubusercontent.com/52989379/163949812-614a61b1-8dd7-4170-b04e-8b80a296fe56.png)

**Comment by huaiyi255** [comment]
2022-04-19 15:34:41,611 - user_handler.py[line:190] - ERROR: Expecting value: line 2 column 1 (char 1)
Traceback (most recent call last):
  File "server\user_handler.py", line 178, in __call__
  File "json\__init__.py", line 348, in loads
  File "json\decoder.py", line 337, in decode
  File "json\decoder.py", line 355, in raw_decode
json.decoder.JSONDecodeError: Expecting value: line 2 column 1 (char 1)

**Comment by huaiyi255** [comment]
> 我的号是正常的 背面 我多加下打​​印看看
刚刚又尝试登录了一下，各种都恢复正常了，这个会不会是服务器段的问题？昨天在登录报错的时候，官网好像也进不去
